Documentação do template
ThundeRatz/ros-python-template pull request #4
Opened 2021-04-20 14:51 UTC by lucastrschneider

Boa tarde galerinha.

O principal objetivo dessa PR é adicionar no README do projeto as instruções para utilização do template e das bibliotecas que preparamos. Além disso, limpamos algumas coisas para ficar menos assustador (o CMakeLists.txt por exemplo) e deixamos apenas o que era necessário.

Se vocês puderem testar os exemplos de código que colocamos no README para garantir que esteja tudo certinho, seria top.

Vou marcar aqui a @mariarezende07 e o @VanderSant para dar uma olhada também, ja que vocês estão fazendo o gabarito e vão precisar testar isso de qualquer jeito.

2021-04-20 14:57 UTC, FelipeGdM approved these changes
Show de boleta

2021-04-20 15:24 UTC, mariarezende07 commented on README.md
> +my_distance_sensor = DistanceSensor('topico/do/sensor/de/distancia')
A gente está ensinando/vai ensinar em algum momento como achar os tópicos?

2021-04-20 15:28 UTC, lucastrschneider commented on README.md
> +my_distance_sensor = DistanceSensor('topico/do/sensor/de/distancia')
Essa é uma excelente pergunta, acho que seria interessante mostrar como usa o `rostopic list` no terminal

Só não tenho certeza se é melhor deixar essa parte em algum tutorial (tipo o de executar o projeto lá que ja abre a simulação), no readme do pacote da simulação, ou nesse readme. O que vocês acham?

2021-04-20 15:41 UTC, mariarezende07 commented on README.md
> +my_distance_sensor = DistanceSensor('topico/do/sensor/de/distancia')
Eu voto por adicionar essa parte nos tutoriais e citar eles no readme

2021-04-20 17:58 UTC, LucasHaug requested changes
Nossa tá muito bonitinha a documentação, falei só umas coisinhas simples.

2021-04-20 17:58 UTC, LucasHaug commented on .vscode/c_cpp_properties.json
> +{
Esse arquivo não precisa tá aqui né?? Já que não tem nada de c/c++

2021-04-20 17:58 UTC, LucasHaug commented on CMakeLists.txt
>  )
Acho que não precisa disso também

2021-04-20 17:58 UTC, LucasHaug commented on CMakeLists.txt
>  ## See http://ros.org/doc/api/catkin/html/user_guide/setup_dot_py.html
Tem umas coisas mais pra cima que acho que dá pra tirar também e colocar o rospy também, aí deixar só:

```cmake
cmake_minimum_required(VERSION 3.0.2)
project(meu_primeiro_robo)

## Find catkin macros and libraries
find_package(catkin REQUIRED COMPONENTS
  rospy
)
```

Tem a parte do `catkin_install_python`, mas acho que não precisa né?

2021-04-20 17:58 UTC, LucasHaug commented on package.xml
>    <!-- Commonly used license strings: -->
Dá pra dar uma limpada aqui nesse arquivo também e colocar um:

```xml
<depend>rospy</depend>
```

2021-04-20 17:58 UTC, LucasHaug commented on README.md
> +Antes de utilizar da interface de controle, é necessário inicializar a variável por meio da função `initialise()`. É recomendável que isso seja feito dentro da função `setup()`
```suggestion
Antes de utilizar a interface de controle, é necessário inicializar a variável por meio da função `initialise()`. É recomendável que isso seja feito dentro da função `setup()`.
```

2021-04-20 17:58 UTC, LucasHaug commented on README.md
> +Para utilizar a biblioteca de controle dos motores, é necessário declarar uma variável do tipo `Motors`. Para fazer isso, é necessário especificar as interfaces de controle com cada motor
```suggestion
Para utilizar a biblioteca de controle dos motores, é necessário declarar uma variável do tipo `Motors`. Para fazer isso, é necessário especificar as interfaces de controle com cada motor.
```

2021-04-20 17:58 UTC, LucasHaug commented on README.md
> +Por fim, os comandos para os motores podem ser enviados por meio da função `drive()`, que recebe como parâmetro dois números inteiros de **-255** (força total para trás) até **255** (força total para
Uma questão batata, porque a gente tá usando de -255 a 255? haushsuhaushuashaus

2021-04-20 17:58 UTC, LucasHaug commented on README.md
> +Juntando tudo, o código de controle deve conter os trechos
```suggestion
Juntando tudo, o código de controle deve conter os trechos:
```

2021-04-20 17:58 UTC, LucasHaug commented on README.md
> +my_distance_sensor = DistanceSensor('topico/do/sensor/de/distancia')
Acho que dá pra por a parte do rostopic list no ROSGazeboGuide, aí os nomes dos tópicos em si se pá dá pra por no README do gazebo_modelo_carrinho, não sei.

2021-04-20 18:14 UTC, VanderSant requested changes
Está muito bom, Xin! ficou bem didático.
De maneira geral, eu não tive muito o que falar ~desculpa corrigir coisas batata~, somente alguns comentários pontuais.

2021-04-20 18:14 UTC, VanderSant commented on README.md
> +
```suggestion
Esse é um exemplo de um projeto simples de ROS feito em Python, que segue a mesma estrutura de um projeto de Arduino

```
Mesmo que o Rafael vai dar uma aula sobre embarcados , tendo em mente o que o @FelipeGdM mencionou durante os tutoriais de instalação do ROSGazeboGuide sobre partimos do principio que os alunos não tem muito conhecimento prévio, acho que seria bom reforçar que o setup é executado somente uma vez e loop (esse é intuitivo) infinitamente.
O que acham?

2021-04-20 18:14 UTC, VanderSant commented on README.md
> +
```suggestion
A partir desse repositório que você construirá o código de controle do seu primeiro robô seguidor de linha simulado! Lembre-se de baixar (ou clonar) no mesmo workspace catkin que você criou enquanto seguia o tutorial de [como executar o projeto](https://thunderatz.github.io/ROSGazeboGuide/HowToRun/README.html).

```
Só um errinho

2021-04-20 18:14 UTC, VanderSant commented on README.md
> +Dentro da pasta **scripts/utils/**, existem alguns módulos de python para facilitar o desenvolvimento do código de controle do carrinho. A seguir, você encontrará uma breve descrição de como usar cad
```suggestion
Dentro da pasta **scripts/utils/**, existem alguns módulos de Python para facilitar o desenvolvimento do código de controle do carrinho. A seguir, você encontrará uma breve descrição de como usar cada um deles.
```
está certo mesmo escrever "módulos de python"? soa um pouco estranho falar que o módulo é do Python por se tratar de uma lib

2021-04-21 02:36 UTC, lucastrschneider commented on README.md
> +my_distance_sensor = DistanceSensor('topico/do/sensor/de/distancia')
> Acho que dá pra por a parte do rostopic list no ROSGazeboGuide, aí os nomes dos tópicos em si se pá dá pra por no README do gazebo_modelo_carrinho, não sei.

A documentação do gazebo_modelo_carrinho vai ter isso sim, é pq ainda não ta pronto kkkkkkkk

Mas acho interessante colocar as intruções do rostopic list no ROSGazeboGuide sim, pq ai eles podem conferir sozinhos também com o modelo deles dps e tals

2021-04-21 02:38 UTC, lucastrschneider commented on README.md
> +Por fim, os comandos para os motores podem ser enviados por meio da função `drive()`, que recebe como parâmetro dois números inteiros de **-255** (força total para trás) até **255** (força total para
Acho que a ideia era ser o mais próximo possivel do arduino, e lá tem a função de AnalogWrite que recebe um byte. Ai pra ficar mais fácil a gente só pegou e espelhou também pros negativos kkkkkkkk

2021-04-21 02:41 UTC, lucastrschneider commented on README.md
> +Dentro da pasta **scripts/utils/**, existem alguns módulos de python para facilitar o desenvolvimento do código de controle do carrinho. A seguir, você encontrará uma breve descrição de como usar cad
Ah, o termo certo para um arquivo python que não é um executável é `module` mesmo se não me engano. Todo arquivo .py é um módulo, e os pacotes são compostos de vários módulos. Se quiser dar uma olhadinha, ta bem explicadinho na [documentação oficial](https://docs.python.org/3/tutorial/modules.html).

2021-04-21 13:06 UTC, FelipeGdM commented on CMakeLists.txt
>  ## See http://ros.org/doc/api/catkin/html/user_guide/setup_dot_py.html
Não temos um `setup.py`, então acho que não precisa msm

2021-04-21 13:06 UTC, FelipeGdM commented on .vscode/c_cpp_properties.json
> +{
Pode pá hahahahaha

2021-04-30 20:41 UTC, LucasHaug commented on package.xml
> +  <maintainer email="lucas.haug@thunderatz.org">Thalles Carneiro</maintainer>
```suggestion
  <maintainer email="thalles.carneiro@thunderatz.org">Thalles Carneiro</maintainer>
  <maintainer email="lucas.schneider@thunderatz.org">Lucas Schneider</maintainer>
  <maintainer email="maria.rezende@thunderatz.org">Maria Fernanda Rezende</maintainer>
  <maintainer email="lucas.haug@thunderatz.org">Lucas Haug</maintainer>
```

2021-05-03 11:29 UTC, FelipeGdM commented on package.xml
> +  <maintainer email="lucas.haug@thunderatz.org">Thalles Carneiro</maintainer>
Eita

2021-05-05 19:00 UTC, mariarezende07 approved these changes
Acho que ta tudo certinho! toop

2021-05-06 21:46 UTC, VanderSant approved these changes
Não tenho mais nada a comentar não, está bem bom!

2021-05-07 16:26 UTC, LucasHaug commented
Faltou só isso daqui: https://github.com/ThundeRatz/ros-python-template/pull/4#discussion_r616891043 de limpar o CMakeLists

2021-05-10 14:44 UTC, LucasHaug approved these changes

2021-05-10 14:44 UTC, merged